<div x-data="{ open: false }" @resize.window="open = window.innerWidth > 640 ? false : none">
    @include('admin.layouts.partials.hamburger')
    <nav class="fixed top-0 bottom-0 bg-gray-600 text-white w-64 flex flex-col overflow-y-auto z-10 transition transform duration-200 ease-in-out sm:translate-x-0"
        :class="{ '-translate-x-64': !open }">
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
        <ul>
            <li>Dashboard</li>
        </ul>
    </nav>
</div>
